// German translations
const de = {
  save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', add: 'Hinzufügen', close: 'Schließen', search: 'Suchen', loading: 'Laden...', saving: 'Speichern...', saved: '✅ Gespeichert', error: 'Fehler', confirm: 'Bestätigen', back: 'Zurück', next: 'Weiter', yes: 'Ja', no: 'Nein', all: 'Alle', none: 'Keine', today: 'Heute', yesterday: 'Gestern', week: 'Woche', month: 'Monat', year: 'Jahr', from: 'Von', to: 'Bis', total: 'Gesamt', export: 'Exportieren', download: 'Herunterladen', upload: 'Hochladen', active: 'Aktiv', inactive: 'Inaktiv', enabled: 'Aktiviert', disabled: 'Deaktiviert', actions: 'Aktionen', details: 'Details', date: 'Datum', time: 'Zeit', name: 'Name', email: 'E-Mail', phone: 'Telefon', address: 'Adresse', city: 'Stadt', notes: 'Notizen', category: 'Kategorie', status: 'Status', type: 'Typ', qty: 'Menge', price: 'Preis', amount: 'Betrag', description: 'Beschreibung', logout: 'Abmelden', noData: 'Keine Daten', rows: 'Zeilen', persons: 'Personen', products: 'Produkte', orders: 'Bestellungen', new_: 'neue', belowThreshold: 'unter Schwelle', reached: 'erreicht', remaining: 'Verbleibend', exceeded: 'Ziel übertroffen!', vsPrevPeriod: 'vs Vorperiode',

  sidebar: {
    dashboard: 'Dashboard', salesLog: 'Verkaufsprotokoll', photoLog: 'Fotoprotokoll', products: 'Produkte', productAnalytics: 'Produktanalyse', teamPerformance: 'Team-Performance', members: 'Mitglieder', central: 'Zentral', secondary: 'Sekundär', storeStock: 'Filialbestand', stockMovements: 'Bestandsbewegungen', bulkUpload: 'Massenupload', initialInventory: 'Anfangsbestand', inventoryAudit: 'Bestandsprüfung', multistore: 'Multistore', tasks: 'Aufgaben', promoCodes: 'Promo-Codes', employees: 'Mitarbeiter', shopify: 'Shopify', ecommerce: 'E-Commerce', vending: 'H24 Automaten', maintenance: 'Wartung', intelligenceAI: 'Intelligence AI', aiManagement: 'AI-Verwaltung', database: 'Datenbank', helpCenter: 'Hilfecenter', settings: 'Einstellungen', notifications: 'Benachrichtigungen', warehouse: 'LAGER', management: 'VERWALTUNG',
  },

  dash: {
    title: '📊 Dashboard', live: '🟢 Live', allStores: 'Alle Filialen', dailyTarget: 'Tagesziel', notifications: 'Benachrichtigungen', readAll: '✓ Alle gelesen', noNotifications: 'Keine Benachrichtigungen', totalRevenue: '💰 Gesamtumsatz', cash: '💵 Bargeld', pos: '💳 Karte', deposit: '🏦 Einzahlung', customers: '👥 Kunden', avgTicket: '🧾 Durchsch. Bon', expenses: '💸 Ausgaben', netProfit: '📈 Nettogewinn', discounts: '🏷️ Gewährte Rabatte', shopifyOnline: '🛍️ Shopify Online', fidelityCards: '💳 Treuekarten', lowStock: '⚠️ Niedriger Bestand', onTotal: 'vom Gesamt', trend7Days: '📅 Trend letzte 7 Tage', top5Products: '🏆 Top 5 Produkte', noSalesDetail: 'Keine Detailverkäufe', sold: 'verkauft', staffOnDuty: '👥 Personal im Dienst', noShifts: 'Keine Schichten', morning: '☀️ Morgen', evening: '🌙 Abend', entry: 'Eintritt', ongoing: 'Laufend', editEntryTime: 'Eintrittszeit bearbeiten', storeBreakdown: '🏪 Umsatz nach Filiale', store: 'Filiale', revenue: 'Umsatz', txn: 'Trans.', avg: 'Durchsch.', hourlyDist: '⏰ Stündliche Kundenverteilung', peakHour: 'Spitzenzeit', nationalityBreak: '🌍 Kundennationalität', channels: '📊 Akquisekanäle', channel: 'Kanal', count: 'Anzahl', pctTotal: '% Gesamt', walkin: '🚶 Laufkunde', social: '📱 Social', google: '🔍 Google', referral: '🤝 Empfehlung', other: '📋 Sonstige',
  },

  sales: {
    title: '🧾 Verkaufsprotokoll', exportExcel: '📊 Excel Export', store: 'Filiale', payment: 'Zahlung', invoiceNum: 'Rech.-Nr.', total: 'Gesamt', subtotal: 'Zwischensumme', employee: 'Mitarbeiter', customerName: 'Kundenname', nationality: 'Nationalität', howFound: 'Wie gefunden', movType: 'Typ', productsCol: 'Produkte', addRow: '+ Zeile', deleteRow: 'Diese Zeile löschen?', deleted: '🗑 Gelöscht', cantDelete: '✗ Löschen nicht möglich',
  },

  db: {
    title: '📊 Datenbank', selectStore: '✗ Filiale auswählen', useEmployeesPage: '✗ Nutzen Sie die Mitarbeiter-Seite', systemGenerated: '✗ Benachrichtigungen werden automatisch generiert', addedRow: '✅ Zeile hinzugefügt', savedField: '✅ Feld gespeichert',
  },

  prod: {
    title: '📦 Produkte', addProduct: 'Produkt hinzufügen', stock: 'Bestand', stockAlert: 'Alarmschwelle', barcode: 'Barcode', costPrice: 'Einkaufspreis', sellPrice: 'Verkaufspreis', activate: 'Aktivieren', deactivate: 'Deaktivieren',
  },

  settings: {
    title: '⚙️ Einstellungen', general: 'Allgemein', employee: 'Mitarbeiter', shopify: 'Shopify', language: '🌐 Sprache', languageDesc: 'Sprache der Benutzeroberfläche auswählen', branding: '🎨 Branding', brandName: 'Markenname', logoLetter: 'Logo-Buchstabe', primaryColor: 'Primärfarbe', vatNumber: 'USt-IdNr.', receiptHeader: 'Bon-Kopfzeile', receiptFooter: 'Bon-Fußzeile', saveBranding: 'Branding speichern', shiftsAndFcu: '🕐 Schichten & FCU', desiredFcu: 'Gewünschtes FCU (€)', morningStart: 'Morgen Beginn', morningEnd: 'Morgen Ende', eveningStart: 'Abend Beginn', eveningEnd: 'Abend Ende', punctualityTolerance: 'Pünktlichkeitstoleranz (Min)', punctualityDesc: 'Mitarbeiter ist "pünktlich" wenn Schicht innerhalb {min} Min geöffnet wird', thresholds: 'Schwellenwerte', stockAlertQty: 'Bestandsalarm (Min-Menge)', discountNotifyPct: 'Rabatt-Benachrichtigung (%)', saveConfig: 'Konfiguration speichern', storeInfo: '🏪 Filialinformationen', storeName: 'Filialname', saveStore: 'Filiale speichern', tabletAccount: '📱 Tablet-Konto', tabletAccountDesc: 'Das Tablet-Konto wird vom iPad der Filiale verwendet. Mitarbeiter identifizieren sich nach dem Login mit ihrer PIN.', tabletEmail: 'Tablet E-Mail', newPassword: 'Neues Passwort (optional)', leaveBlank: 'Leer lassen um beizubehalten', accountConfigured: 'Konto konfiguriert — Tablet kann sich anmelden', updatePassword: '🔑 Passwort aktualisieren', noTablet: 'Kein Tablet-Konto konfiguriert', goToEmployees: 'Gehen Sie zu Mitarbeiterverwaltung → Filialkonto', bonuses: '💰 Mitarbeiter-Boni', salesCommission: 'Verkaufsprovision (%)', shiftBonus: 'Schichtbonus (€)', avgSaleThreshold: 'Durchsch. Verkaufsschwelle (€)', saveBonus: 'Boni speichern', employeeFunctions: '👥 Mitarbeiterfunktionen', employeeFunctionsDesc: 'Jede Funktion für Mitarbeiter konfigurieren', saveAll: '💾 Alles speichern', disabledFunctionsHint: 'Deaktivierte Funktionen erscheinen nicht im Mitarbeiter-Dashboard.', enableToConfig: '⚠️ Funktion aktivieren um Parameter zu konfigurieren', shopifyIntegration: '🛍️ Shopify-Integration', shopifyDesc: 'Verbinden Sie Ihren Shopify-Store um Bestellungen direkt aus BrainWare zu verwalten.', shopifyDomain: 'Shopify Store Domain', shopifyDomainHint: 'Nur die Domain, z.B.: meinshop.myshopify.com', accessToken: 'Access Token (Admin API)', autoSync: 'Automatische Synchronisation aktiv', saveShopify: 'Shopify speichern', viewOrders: '👁️ Bestellungen anzeigen',
    feat_pos: 'POS / Verkauf', feat_pos_desc: 'Verkäufe registrieren', feat_shopify: 'Shopify-Bestellungen', feat_shopify_desc: 'Online-Bestellungen verwalten', feat_fidelity: 'Treuekarten', feat_fidelity_desc: 'Treuekartenverwaltung', feat_inventory: 'Inventurzählung', feat_inventory_desc: 'Inventar und Produktzählung', feat_stock: 'Nachfüllen', feat_stock_desc: 'Mengen zu Produkten hinzufügen', feat_transfers: 'Transfers', feat_transfers_desc: 'Produkte zwischen Filialen transferieren', feat_expenses: 'Ausgaben', feat_expenses_desc: 'Ausgaben während der Schicht erfassen', feat_maintenance: 'Wartung', feat_maintenance_desc: 'Checkliste und Wartung', feat_photos: 'Fotoprotokoll', feat_photos_desc: 'Kassenfotos hochladen', feat_vending: 'Automaten', feat_vending_desc: 'H24-Automatenverwaltung', feat_ai: 'KI-Assistent', feat_ai_desc: 'Zugang zum KI-Assistenten', feat_calendar: 'Freie Tage', feat_calendar_desc: 'Urlaubs- und Freistellungsanträge', feat_checkout: 'Auschecken', feat_checkout_desc: 'Gehen ohne Schicht zu schließen',
  },

  ai: {
    title: 'Intelligence AI', beta: 'BETA', dataLoaded: '✅ Daten geladen', loadingData: 'Laden...', freeRequests: 'kostenlose Anfragen', askAboutData: 'Fragen Sie etwas über Ihre Daten...', send: 'Senden', howCanIHelp: 'Wie kann ich Ihnen heute helfen?', analyzeDesc: 'Analysieren Sie Verkäufe, Performance, Inventar Ihrer Filiale in natürlicher Sprache', suggestion1: 'Heutige Verkaufsanalyse', suggestion2: 'Niedrige Bestände', suggestion3: 'Mitarbeiter-Performance', suggestion4: 'Wöchentlicher Umsatztrend', serviceDown: '⏳ AI-Dienst vorübergehend nicht verfügbar', serviceDownDesc: 'Das tägliche Kontingent wurde erreicht. Es wird innerhalb weniger Stunden zurückgesetzt.', dailyLimitReached: '🚫 Tageslimit erreicht', almostAtLimit: '⚠️ Fast am Limit', newChat: '+ Neu',
  },

  emp: { title: '👤 Mitarbeiter', addEmployee: 'Mitarbeiter hinzufügen', fullName: 'Vollständiger Name', pin: 'PIN', role: 'Rolle', store: 'Filiale' },

  empApp: {
    home: 'Home', sale: 'Verkauf', inventory: 'Inventar', maintenance: 'Wartung', restock: 'Nachfüllen', aiAssistant: '🤖 KI-Assistent', safeMode: '🔒 Sicherer Modus', safeDesc: 'Betriebshilfe · Kein Zugriff auf Geschäftsdaten', hello: 'Hallo! Wie kann ich Ihnen helfen?', procAndTech: 'Verfahren, technische Probleme, Kundenverwaltung und mehr', noSalesAccess: '🔒 Ich habe keinen Zugriff auf Verkaufs- oder Geschäftsdaten. Ich kann nur bei Betriebsverfahren und technischen Problemen helfen.', askSomething: 'Fragen Sie etwas...', limitReached: 'Limit für heute erreicht', dailyLimitMsg: '⏳ Sie haben das tägliche Anfragelimit erreicht. Anfragen werden um Mitternacht zurückgesetzt.',
  },

  members: { title: '💳 Mitglieder', addMember: 'Mitglied hinzufügen', points: 'Punkte', totalSpent: 'Gesamtausgaben' },

  wh: { central: '🏭 Zentrallager', secondary: '📦 Nebenlager', storeStock: '🏪 Filialbestand', movements: '📋 Bestandsbewegungen', sku: 'SKU', units: 'Einheiten', value: 'Wert', lowItems: 'niedrig', outOfStock: 'ausverkauft' },

  notif: { title: '🔔 Benachrichtigungen', markRead: 'Als gelesen markieren', markAllRead: 'Alle als gelesen markieren', noNotifications: 'Keine Benachrichtigungen' },
} as const

export default de
