// Spanish translations
const es = {
  save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', add: 'Añadir', close: 'Cerrar', search: 'Buscar', loading: 'Cargando...', saving: 'Guardando...', saved: '✅ Guardado', error: 'Error', confirm: 'Confirmar', back: 'Atrás', next: 'Siguiente', yes: 'Sí', no: 'No', all: 'Todos', none: 'Ninguno', today: 'Hoy', yesterday: 'Ayer', week: 'Semana', month: 'Mes', year: 'Año', from: 'Desde', to: 'Hasta', total: 'Total', export: 'Exportar', download: 'Descargar', upload: 'Cargar', active: 'Activo', inactive: 'Inactivo', enabled: 'Activado', disabled: 'Desactivado', actions: 'Acciones', details: 'Detalles', date: 'Fecha', time: 'Hora', name: 'Nombre', email: 'Email', phone: 'Teléfono', address: 'Dirección', city: 'Ciudad', notes: 'Notas', category: 'Categoría', status: 'Estado', type: 'Tipo', qty: 'Cant.', price: 'Precio', amount: 'Importe', description: 'Descripción', logout: 'Cerrar sesión', noData: 'Sin datos', rows: 'filas', persons: 'personas', products: 'Productos', orders: 'pedidos', new_: 'nuevas', belowThreshold: 'bajo umbral', reached: 'alcanzado', remaining: 'Faltan', exceeded: '¡Objetivo superado!', vsPrevPeriod: 'vs período ant.',

  sidebar: {
    dashboard: 'Panel', salesLog: 'Registro de ventas', photoLog: 'Registro de fotos', products: 'Productos', productAnalytics: 'Análisis de productos', teamPerformance: 'Rendimiento del equipo', members: 'Miembros', central: 'Central', secondary: 'Secundario', storeStock: 'Stock de tienda', stockMovements: 'Movimientos de stock', bulkUpload: 'Carga masiva', initialInventory: 'Inventario inicial', inventoryAudit: 'Auditoría de inventario', multistore: 'Multitienda', tasks: 'Tareas', promoCodes: 'Códigos promo', employees: 'Empleados', shopify: 'Shopify', ecommerce: 'E-commerce', vending: 'H24 Máquinas', maintenance: 'Mantenimiento', intelligenceAI: 'Inteligencia IA', aiManagement: 'Gestión IA', database: 'Base de datos', helpCenter: 'Centro de ayuda', settings: 'Ajustes', notifications: 'Notificaciones', warehouse: 'ALMACÉN', management: 'GESTIÓN',
  },

  dash: {
    title: '📊 Panel', live: '🟢 En vivo', allStores: 'Todas las tiendas', dailyTarget: 'Objetivo diario', notifications: 'Notificaciones', readAll: '✓ Todo leído', noNotifications: 'Sin notificaciones', totalRevenue: '💰 Ingresos totales', cash: '💵 Efectivo', pos: '💳 Tarjeta', deposit: '🏦 Depósito', customers: '👥 Clientes', avgTicket: '🧾 Ticket medio', expenses: '💸 Gastos', netProfit: '📈 Beneficio neto', discounts: '🏷️ Descuentos', shopifyOnline: '🛍️ Shopify Online', fidelityCards: '💳 Tarjetas fidelidad', lowStock: '⚠️ Stock bajo', onTotal: 'del total', trend7Days: '📅 Tendencia últimos 7 días', top5Products: '🏆 Top 5 Productos', noSalesDetail: 'Sin ventas detalladas', sold: 'vendidos', staffOnDuty: '👥 Personal en servicio', noShifts: 'Sin turnos registrados', morning: '☀️ Mañana', evening: '🌙 Noche', entry: 'Entrada', ongoing: 'En curso', editEntryTime: 'Editar hora de entrada', storeBreakdown: '🏪 Ingresos por tienda', store: 'Tienda', revenue: 'Ingresos', txn: 'Trans.', avg: 'Media', hourlyDist: '⏰ Distribución horaria de clientes', peakHour: 'Hora punta', nationalityBreak: '🌍 Nacionalidad de clientes', channels: '📊 Canales de adquisición', channel: 'Canal', count: 'Recuento', pctTotal: '% Total', walkin: '🚶 Paso', social: '📱 Social', google: '🔍 Google', referral: '🤝 Recomendación', other: '📋 Otro',
  },

  sales: {
    title: '🧾 Registro de ventas', exportExcel: '📊 Exportar Excel', store: 'Tienda', payment: 'Pago', invoiceNum: 'N° Fact.', total: 'Total', subtotal: 'Subtotal', employee: 'Empleado', customerName: 'Nombre cliente', nationality: 'Nacionalidad', howFound: 'Cómo nos encontró', movType: 'Tipo', productsCol: 'Productos', addRow: '+ Fila', deleteRow: '¿Eliminar esta fila?', deleted: '🗑 Eliminado', cantDelete: '✗ No se puede eliminar',
  },

  db: {
    title: '📊 Base de datos', selectStore: '✗ Selecciona una tienda', useEmployeesPage: '✗ Usa la página de Empleados para crear usuarios', systemGenerated: '✗ Las notificaciones son generadas por el sistema', addedRow: '✅ Fila añadida', savedField: '✅ Campo guardado',
  },

  prod: {
    title: '📦 Productos', addProduct: 'Añadir producto', stock: 'Stock', stockAlert: 'Umbral de alerta', barcode: 'Código de barras', costPrice: 'Precio de coste', sellPrice: 'Precio de venta', activate: 'Activar', deactivate: 'Desactivar',
  },

  settings: {
    title: '⚙️ Ajustes', general: 'General', employee: 'Empleado', shopify: 'Shopify', language: '🌐 Idioma', languageDesc: 'Selecciona el idioma de la interfaz', branding: '🎨 Marca', brandName: 'Nombre de marca', logoLetter: 'Letra del logo', primaryColor: 'Color principal', vatNumber: 'NIF/CIF', receiptHeader: 'Encabezado del recibo', receiptFooter: 'Pie del recibo', saveBranding: 'Guardar marca', shiftsAndFcu: '🕐 Turnos y FCU', desiredFcu: 'FCU deseado (€)', morningStart: 'Inicio mañana', morningEnd: 'Fin mañana', eveningStart: 'Inicio noche', eveningEnd: 'Fin noche', punctualityTolerance: 'Tolerancia puntualidad (min)', punctualityDesc: 'El empleado es "puntual" si abre el turno dentro de {min} min', thresholds: 'Umbrales', stockAlertQty: 'Alerta inventario (cant. mín)', discountNotifyPct: 'Notificación descuento (%)', saveConfig: 'Guardar configuración', storeInfo: '🏪 Información de tienda', storeName: 'Nombre de tienda', saveStore: 'Guardar tienda', tabletAccount: '📱 Cuenta tablet', tabletAccountDesc: 'La cuenta tablet es usada por el iPad de la tienda. Los empleados se identifican con su PIN después del login.', tabletEmail: 'Email tablet', newPassword: 'Nueva contraseña (opcional)', leaveBlank: 'Dejar vacío para mantener', accountConfigured: 'Cuenta configurada — la tablet puede conectarse', updatePassword: '🔑 Actualizar contraseña', noTablet: 'Ninguna cuenta tablet configurada', goToEmployees: 'Ve a Gestión de empleados → Cuenta de tienda', bonuses: '💰 Bonificaciones', salesCommission: 'Comisión ventas (%)', shiftBonus: 'Bonus por turno (€)', avgSaleThreshold: 'Umbral venta media (€)', saveBonus: 'Guardar bonificaciones', employeeFunctions: '👥 Funciones del empleado', employeeFunctionsDesc: 'Configura cada función accesible a los empleados', saveAll: '💾 Guardar todo', disabledFunctionsHint: 'Las funciones desactivadas no aparecerán en el panel del empleado.', enableToConfig: '⚠️ Activa la función para configurar parámetros', shopifyIntegration: '🛍️ Integración Shopify', shopifyDesc: 'Conecta tu tienda Shopify para gestionar pedidos directamente desde BrainWare.', shopifyDomain: 'Dominio Shopify', shopifyDomainHint: 'Solo el dominio, ej: mitienda.myshopify.com', accessToken: 'Access Token (Admin API)', autoSync: 'Sincronización automática activa', saveShopify: 'Guardar Shopify', viewOrders: '👁️ Ver pedidos',
    feat_pos: 'POS / Venta', feat_pos_desc: 'Registrar ventas y gestionar el carrito', feat_shopify: 'Pedidos Shopify', feat_shopify_desc: 'Gestión de pedidos online', feat_fidelity: 'Tarjetas fidelidad', feat_fidelity_desc: 'Gestión de tarjetas de fidelidad', feat_inventory: 'Conteo inventario', feat_inventory_desc: 'Inventario y conteo de productos', feat_stock: 'Reposición', feat_stock_desc: 'Añadir cantidades a productos', feat_transfers: 'Transferencias', feat_transfers_desc: 'Transferir productos entre tiendas', feat_expenses: 'Gastos', feat_expenses_desc: 'Registrar gastos durante el turno', feat_maintenance: 'Mantenimiento', feat_maintenance_desc: 'Checklist y mantenimiento', feat_photos: 'Registro de fotos', feat_photos_desc: 'Subir fotos de caja', feat_vending: 'Máquinas expendedoras', feat_vending_desc: 'Gestión de máquinas H24', feat_ai: 'Asistente IA', feat_ai_desc: 'Acceso al asistente IA', feat_calendar: 'Días libres', feat_calendar_desc: 'Solicitudes de permisos y vacaciones', feat_checkout: 'Salida', feat_checkout_desc: 'Salir sin cerrar el turno',
  },

  ai: {
    title: 'Inteligencia IA', beta: 'BETA', dataLoaded: '✅ Datos cargados', loadingData: 'Cargando...', freeRequests: 'solicitudes gratuitas', askAboutData: 'Pregunta algo sobre tus datos...', send: 'Enviar', howCanIHelp: '¿Cómo puedo ayudarte hoy?', analyzeDesc: 'Analiza ventas, rendimiento, inventario de tu tienda en lenguaje natural', suggestion1: 'Análisis de ventas de hoy', suggestion2: 'Productos con bajo stock', suggestion3: 'Rendimiento de empleados', suggestion4: 'Tendencia de ingresos semanal', serviceDown: '⏳ Servicio IA temporalmente no disponible', serviceDownDesc: 'La cuota diaria ha sido alcanzada. Se reinicia automáticamente en unas horas.', dailyLimitReached: '🚫 Límite diario alcanzado', almostAtLimit: '⚠️ Casi en el límite', newChat: '+ Nuevo',
  },

  emp: { title: '👤 Empleados', addEmployee: 'Añadir empleado', fullName: 'Nombre completo', pin: 'PIN', role: 'Rol', store: 'Tienda' },

  empApp: {
    home: 'Inicio', sale: 'Venta', inventory: 'Inventario', maintenance: 'Mantenimiento', restock: 'Reposición', aiAssistant: '🤖 Asistente IA', safeMode: '🔒 Modo seguro', safeDesc: 'Ayuda operativa · Sin acceso a datos comerciales', hello: '¡Hola! ¿Cómo puedo ayudarte?', procAndTech: 'Procedimientos, problemas técnicos, gestión de clientes y más', noSalesAccess: '🔒 No tengo acceso a ventas, ingresos o datos comerciales. Solo puedo ayudar con procedimientos operativos y problemas técnicos.', askSomething: 'Pregunta algo...', limitReached: 'Límite alcanzado por hoy', dailyLimitMsg: '⏳ Has alcanzado el límite diario de solicitudes. Se reinician a medianoche.',
  },

  members: { title: '💳 Miembros', addMember: 'Añadir miembro', points: 'Puntos', totalSpent: 'Gasto total' },

  wh: { central: '🏭 Almacén central', secondary: '📦 Almacenes secundarios', storeStock: '🏪 Stock de tienda', movements: '📋 Movimientos de stock', sku: 'SKU', units: 'unidades', value: 'valor', lowItems: 'bajos', outOfStock: 'agotados' },

  notif: { title: '🔔 Notificaciones', markRead: 'Marcar como leído', markAllRead: 'Marcar todo como leído', noNotifications: 'Sin notificaciones' },
} as const

export default es
