// French translations
const fr = {
  save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', add: 'Ajouter', close: 'Fermer', search: 'Rechercher', loading: 'Chargement...', saving: 'Enregistrement...', saved: '✅ Enregistré', error: 'Erreur', confirm: 'Confirmer', back: 'Retour', next: 'Suivant', yes: 'Oui', no: 'Non', all: 'Tous', none: 'Aucun', today: 'Aujourd\'hui', yesterday: 'Hier', week: 'Semaine', month: 'Mois', year: 'Année', from: 'De', to: 'À', total: 'Total', export: 'Exporter', download: 'Télécharger', upload: 'Charger', active: 'Actif', inactive: 'Inactif', enabled: 'Activé', disabled: 'Désactivé', actions: 'Actions', details: 'Détails', date: 'Date', time: 'Heure', name: 'Nom', email: 'E-mail', phone: 'Téléphone', address: 'Adresse', city: 'Ville', notes: 'Notes', category: 'Catégorie', status: 'Statut', type: 'Type', qty: 'Qté', price: 'Prix', amount: 'Montant', description: 'Description', logout: 'Déconnexion', noData: 'Aucune donnée', rows: 'lignes', persons: 'personnes', products: 'Produits', orders: 'commandes', new_: 'nouvelles', belowThreshold: 'sous le seuil', reached: 'atteint', remaining: 'Restant', exceeded: 'Objectif dépassé !', vsPrevPeriod: 'vs période préc.',

  sidebar: {
    dashboard: 'Tableau de bord', salesLog: 'Registre des ventes', photoLog: 'Registre photos', products: 'Produits', productAnalytics: 'Analyse produits', teamPerformance: 'Performance équipe', members: 'Membres', central: 'Central', secondary: 'Secondaire', storeStock: 'Stock magasin', stockMovements: 'Mouvements stock', bulkUpload: 'Import en masse', initialInventory: 'Inventaire initial', inventoryAudit: 'Audit inventaire', multistore: 'Multimagasin', tasks: 'Tâches', promoCodes: 'Codes promo', employees: 'Employés', shopify: 'Shopify', ecommerce: 'E-commerce', vending: 'H24 Distributeurs', maintenance: 'Maintenance', intelligenceAI: 'Intelligence IA', aiManagement: 'Gestion IA', database: 'Base de données', helpCenter: 'Centre d\'aide', settings: 'Paramètres', notifications: 'Notifications', warehouse: 'ENTREPÔT', management: 'GESTION',
  },

  dash: {
    title: '📊 Tableau de bord', live: '🟢 En direct', allStores: 'Tous les magasins', dailyTarget: 'Objectif journalier', notifications: 'Notifications', readAll: '✓ Tout lu', noNotifications: 'Aucune notification', totalRevenue: '💰 Chiffre d\'affaires', cash: '💵 Espèces', pos: '💳 Carte', deposit: '🏦 Dépôt', customers: '👥 Clients', avgTicket: '🧾 Ticket moyen', expenses: '💸 Dépenses', netProfit: '📈 Bénéfice net', discounts: '🏷️ Remises accordées', shopifyOnline: '🛍️ Shopify en ligne', fidelityCards: '💳 Cartes fidélité', lowStock: '⚠️ Stock bas', onTotal: 'du total', trend7Days: '📅 Tendance 7 derniers jours', top5Products: '🏆 Top 5 Produits', noSalesDetail: 'Aucune vente détaillée', sold: 'vendus', staffOnDuty: '👥 Personnel en service', noShifts: 'Aucun créneau enregistré', morning: '☀️ Matin', evening: '🌙 Soir', entry: 'Entrée', ongoing: 'En cours', editEntryTime: 'Modifier l\'heure d\'entrée', storeBreakdown: '🏪 CA par magasin', store: 'Magasin', revenue: 'CA', txn: 'Trans.', avg: 'Moy.', hourlyDist: '⏰ Distribution horaire clients', peakHour: 'Heure de pointe', nationalityBreak: '🌍 Nationalité clients', channels: '📊 Canaux d\'acquisition', channel: 'Canal', count: 'Nombre', pctTotal: '% Total', walkin: '🚶 Passage', social: '📱 Réseaux sociaux', google: '🔍 Google', referral: '🤝 Recommandation', other: '📋 Autre',
  },

  sales: {
    title: '🧾 Registre des ventes', exportExcel: '📊 Export Excel', store: 'Magasin', payment: 'Paiement', invoiceNum: 'N° Fact.', total: 'Total', subtotal: 'Sous-total', employee: 'Employé', customerName: 'Nom client', nationality: 'Nationalité', howFound: 'Comment trouvé', movType: 'Type', productsCol: 'Produits', addRow: '+ Ligne', deleteRow: 'Supprimer cette ligne ?', deleted: '🗑 Supprimé', cantDelete: '✗ Impossible de supprimer',
  },

  db: {
    title: '📊 Base de données', selectStore: '✗ Sélectionnez un magasin', useEmployeesPage: '✗ Utilisez la page Employés pour créer des utilisateurs', systemGenerated: '✗ Les notifications sont générées par le système', addedRow: '✅ Ligne ajoutée', savedField: '✅ Champ enregistré',
  },

  prod: {
    title: '📦 Produits', addProduct: 'Ajouter un produit', stock: 'Stock', stockAlert: 'Seuil d\'alerte', barcode: 'Code-barres', costPrice: 'Prix d\'achat', sellPrice: 'Prix de vente', activate: 'Activer', deactivate: 'Désactiver',
  },

  settings: {
    title: '⚙️ Paramètres', general: 'Général', employee: 'Employé', shopify: 'Shopify', language: '🌐 Langue', languageDesc: 'Sélectionnez la langue de l\'interface', branding: '🎨 Image de marque', brandName: 'Nom de la marque', logoLetter: 'Lettre du logo', primaryColor: 'Couleur principale', vatNumber: 'N° TVA', receiptHeader: 'En-tête du reçu', receiptFooter: 'Pied du reçu', saveBranding: 'Enregistrer l\'image de marque', shiftsAndFcu: '🕐 Créneaux & FCU', desiredFcu: 'FCU souhaité (€)', morningStart: 'Début matin', morningEnd: 'Fin matin', eveningStart: 'Début soir', eveningEnd: 'Fin soir', punctualityTolerance: 'Tolérance ponctualité (min)', punctualityDesc: 'L\'employé est "à l\'heure" si le créneau ouvre dans les {min} min', thresholds: 'Seuils', stockAlertQty: 'Alerte inventaire (qté min)', discountNotifyPct: 'Notification remise (%)', saveConfig: 'Enregistrer configuration', storeInfo: '🏪 Informations magasin', storeName: 'Nom du magasin', saveStore: 'Enregistrer magasin', tabletAccount: '📱 Compte tablette', tabletAccountDesc: 'Le compte tablette est utilisé par l\'iPad du magasin. Les employés s\'identifient avec leur PIN après connexion.', tabletEmail: 'E-mail tablette', newPassword: 'Nouveau mot de passe (optionnel)', leaveBlank: 'Laissez vide pour garder l\'actuel', accountConfigured: 'Compte configuré — la tablette peut se connecter', updatePassword: '🔑 Mettre à jour le mot de passe', noTablet: 'Aucun compte tablette configuré', goToEmployees: 'Allez dans Gestion des employés → Compte magasin', bonuses: '💰 Bonus employés', salesCommission: 'Commission ventes (%)', shiftBonus: 'Bonus créneau (€)', avgSaleThreshold: 'Seuil vente moy. (€)', saveBonus: 'Enregistrer bonus', employeeFunctions: '👥 Fonctions employé', employeeFunctionsDesc: 'Configurez chaque fonction accessible aux employés', saveAll: '💾 Tout enregistrer', disabledFunctionsHint: 'Les fonctions désactivées n\'apparaîtront pas dans le tableau de bord employé.', enableToConfig: '⚠️ Activez la fonction pour configurer les paramètres', shopifyIntegration: '🛍️ Intégration Shopify', shopifyDesc: 'Connectez votre boutique Shopify pour gérer les commandes directement depuis BrainWare.', shopifyDomain: 'Domaine Shopify', shopifyDomainHint: 'Le domaine uniquement, ex: maboutique.myshopify.com', accessToken: 'Access Token (Admin API)', autoSync: 'Synchronisation automatique activée', saveShopify: 'Enregistrer Shopify', viewOrders: '👁️ Voir les commandes',
    feat_pos: 'POS / Vente', feat_pos_desc: 'Enregistrer des ventes', feat_shopify: 'Commandes Shopify', feat_shopify_desc: 'Gestion des commandes en ligne', feat_fidelity: 'Cartes fidélité', feat_fidelity_desc: 'Gestion des cartes fidélité', feat_inventory: 'Comptage inventaire', feat_inventory_desc: 'Inventaire et comptage produits', feat_stock: 'Réapprovisionnement', feat_stock_desc: 'Ajouter des quantités aux produits', feat_transfers: 'Transferts', feat_transfers_desc: 'Transférer des produits entre magasins', feat_expenses: 'Dépenses', feat_expenses_desc: 'Enregistrer les dépenses pendant le créneau', feat_maintenance: 'Maintenance', feat_maintenance_desc: 'Checklist et maintenance', feat_photos: 'Registre photos', feat_photos_desc: 'Charger les photos de caisse', feat_vending: 'Distributeurs', feat_vending_desc: 'Gestion des distributeurs H24', feat_ai: 'Assistant IA', feat_ai_desc: 'Accès à l\'assistant IA', feat_calendar: 'Jours de congé', feat_calendar_desc: 'Demandes de congés et vacances', feat_checkout: 'Sortie', feat_checkout_desc: 'Partir sans fermer le créneau',
  },

  ai: {
    title: 'Intelligence IA', beta: 'BÊTA', dataLoaded: '✅ Données chargées', loadingData: 'Chargement...', freeRequests: 'requêtes gratuites', askAboutData: 'Posez une question sur vos données...', send: 'Envoyer', howCanIHelp: 'Comment puis-je vous aider aujourd\'hui ?', analyzeDesc: 'Analysez ventes, performance, inventaire de votre magasin en langage naturel', suggestion1: 'Analyse des ventes du jour', suggestion2: 'Produits en rupture', suggestion3: 'Performance des employés', suggestion4: 'Tendance CA hebdomadaire', serviceDown: '⏳ Service IA temporairement indisponible', serviceDownDesc: 'Le quota journalier a été atteint. Il se réinitialise dans quelques heures.', dailyLimitReached: '🚫 Limite journalière atteinte', almostAtLimit: '⚠️ Presque à la limite', newChat: '+ Nouveau',
  },

  emp: { title: '👤 Employés', addEmployee: 'Ajouter un employé', fullName: 'Nom complet', pin: 'PIN', role: 'Rôle', store: 'Magasin' },

  empApp: {
    home: 'Accueil', sale: 'Vente', inventory: 'Inventaire', maintenance: 'Maintenance', restock: 'Réappro.', aiAssistant: '🤖 Assistant IA', safeMode: '🔒 Mode sécurisé', safeDesc: 'Aide opérationnelle · Pas d\'accès aux données commerciales', hello: 'Bonjour ! Comment puis-je vous aider ?', procAndTech: 'Procédures, problèmes techniques, gestion client et plus', noSalesAccess: '🔒 Je n\'ai pas accès aux ventes, revenus ou données commerciales. Je ne peux aider qu\'avec les procédures opérationnelles.', askSomething: 'Posez une question...', limitReached: 'Limite atteinte pour aujourd\'hui', dailyLimitMsg: '⏳ Vous avez atteint la limite de requêtes quotidiennes. Les requêtes se réinitialisent à minuit.',
  },

  members: { title: '💳 Membres', addMember: 'Ajouter un membre', points: 'Points', totalSpent: 'Total dépensé' },

  wh: { central: '🏭 Entrepôt central', secondary: '📦 Entrepôts secondaires', storeStock: '🏪 Stock magasin', movements: '📋 Mouvements de stock', sku: 'SKU', units: 'unités', value: 'valeur', lowItems: 'bas', outOfStock: 'en rupture' },

  notif: { title: '🔔 Notifications', markRead: 'Marquer comme lu', markAllRead: 'Tout marquer comme lu', noNotifications: 'Aucune notification' },
} as const

export default fr
