// Portuguese translations
const pt = {
  save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', add: 'Adicionar', close: 'Fechar', search: 'Buscar', loading: 'Carregando...', saving: 'Salvando...', saved: '✅ Salvo', error: 'Erro', confirm: 'Confirmar', back: 'Voltar', next: 'Próximo', yes: 'Sim', no: 'Não', all: 'Todos', none: 'Nenhum', today: 'Hoje', yesterday: 'Ontem', week: 'Semana', month: 'Mês', year: 'Ano', from: 'De', to: 'Até', total: 'Total', export: 'Exportar', download: 'Baixar', upload: 'Carregar', active: 'Ativo', inactive: 'Inativo', enabled: 'Ativado', disabled: 'Desativado', actions: 'Ações', details: 'Detalhes', date: 'Data', time: 'Hora', name: 'Nome', email: 'E-mail', phone: 'Telefone', address: 'Endereço', city: 'Cidade', notes: 'Notas', category: 'Categoria', status: 'Status', type: 'Tipo', qty: 'Qtd', price: 'Preço', amount: 'Valor', description: 'Descrição', logout: 'Sair', noData: 'Sem dados', rows: 'linhas', persons: 'pessoas', products: 'Produtos', orders: 'pedidos', new_: 'novos', belowThreshold: 'abaixo do limite', reached: 'atingido', remaining: 'Faltam', exceeded: 'Objetivo superado!', vsPrevPeriod: 'vs período ant.',

  sidebar: {
    dashboard: 'Painel', salesLog: 'Registro de vendas', photoLog: 'Registro de fotos', products: 'Produtos', productAnalytics: 'Análise de produtos', teamPerformance: 'Desempenho da equipe', members: 'Membros', central: 'Central', secondary: 'Secundário', storeStock: 'Estoque da loja', stockMovements: 'Movimentos de estoque', bulkUpload: 'Upload em massa', initialInventory: 'Inventário inicial', inventoryAudit: 'Auditoria de inventário', multistore: 'Multiloja', tasks: 'Tarefas', promoCodes: 'Códigos promo', employees: 'Funcionários', shopify: 'Shopify', ecommerce: 'E-commerce', vending: 'H24 Máquinas', maintenance: 'Manutenção', intelligenceAI: 'Inteligência IA', aiManagement: 'Gestão IA', database: 'Banco de dados', helpCenter: 'Central de ajuda', settings: 'Configurações', notifications: 'Notificações', warehouse: 'ARMAZÉM', management: 'GESTÃO',
  },

  dash: {
    title: '📊 Painel', live: '🟢 Ao vivo', allStores: 'Todas as lojas', dailyTarget: 'Meta diária', notifications: 'Notificações', readAll: '✓ Tudo lido', noNotifications: 'Sem notificações', totalRevenue: '💰 Receita total', cash: '💵 Dinheiro', pos: '💳 Cartão', deposit: '🏦 Depósito', customers: '👥 Clientes', avgTicket: '🧾 Ticket médio', expenses: '💸 Despesas', netProfit: '📈 Lucro líquido', discounts: '🏷️ Descontos', shopifyOnline: '🛍️ Shopify Online', fidelityCards: '💳 Cartões fidelidade', lowStock: '⚠️ Estoque baixo', onTotal: 'do total', trend7Days: '📅 Tendência últimos 7 dias', top5Products: '🏆 Top 5 Produtos', noSalesDetail: 'Sem vendas detalhadas', sold: 'vendidos', staffOnDuty: '👥 Equipe em serviço', noShifts: 'Sem turnos registrados', morning: '☀️ Manhã', evening: '🌙 Noite', entry: 'Entrada', ongoing: 'Em andamento', editEntryTime: 'Editar hora de entrada', storeBreakdown: '🏪 Receita por loja', store: 'Loja', revenue: 'Receita', txn: 'Trans.', avg: 'Média', hourlyDist: '⏰ Distribuição horária de clientes', peakHour: 'Horário de pico', nationalityBreak: '🌍 Nacionalidade dos clientes', channels: '📊 Canais de aquisição', channel: 'Canal', count: 'Contagem', pctTotal: '% Total', walkin: '🚶 Passantes', social: '📱 Social', google: '🔍 Google', referral: '🤝 Indicação', other: '📋 Outro',
  },

  sales: {
    title: '🧾 Registro de vendas', exportExcel: '📊 Exportar Excel', store: 'Loja', payment: 'Pagamento', invoiceNum: 'N° Nota', total: 'Total', subtotal: 'Subtotal', employee: 'Funcionário', customerName: 'Nome do cliente', nationality: 'Nacionalidade', howFound: 'Como encontrou', movType: 'Tipo', productsCol: 'Produtos', addRow: '+ Linha', deleteRow: 'Excluir esta linha?', deleted: '🗑 Excluído', cantDelete: '✗ Não é possível excluir',
  },

  db: {
    title: '📊 Banco de dados', selectStore: '✗ Selecione uma loja', useEmployeesPage: '✗ Use a página de Funcionários para criar usuários', systemGenerated: '✗ As notificações são geradas pelo sistema', addedRow: '✅ Linha adicionada', savedField: '✅ Campo salvo',
  },

  prod: {
    title: '📦 Produtos', addProduct: 'Adicionar produto', stock: 'Estoque', stockAlert: 'Limite de alerta', barcode: 'Código de barras', costPrice: 'Preço de custo', sellPrice: 'Preço de venda', activate: 'Ativar', deactivate: 'Desativar',
  },

  settings: {
    title: '⚙️ Configurações', general: 'Geral', employee: 'Funcionário', shopify: 'Shopify', language: '🌐 Idioma', languageDesc: 'Selecione o idioma da interface', branding: '🎨 Marca', brandName: 'Nome da marca', logoLetter: 'Letra do logo', primaryColor: 'Cor principal', vatNumber: 'CNPJ/CPF', receiptHeader: 'Cabeçalho do recibo', receiptFooter: 'Rodapé do recibo', saveBranding: 'Salvar marca', shiftsAndFcu: '🕐 Turnos & FCU', desiredFcu: 'FCU desejado (€)', morningStart: 'Início manhã', morningEnd: 'Fim manhã', eveningStart: 'Início noite', eveningEnd: 'Fim noite', punctualityTolerance: 'Tolerância de pontualidade (min)', punctualityDesc: 'Funcionário é "pontual" se abrir turno dentro de {min} min', thresholds: 'Limites', stockAlertQty: 'Alerta de inventário (qtd mín)', discountNotifyPct: 'Notificação desconto (%)', saveConfig: 'Salvar configuração', storeInfo: '🏪 Informações da loja', storeName: 'Nome da loja', saveStore: 'Salvar loja', tabletAccount: '📱 Conta do tablet', tabletAccountDesc: 'A conta do tablet é usada pelo iPad da loja. Os funcionários se identificam com seu PIN após o login.', tabletEmail: 'E-mail do tablet', newPassword: 'Nova senha (opcional)', leaveBlank: 'Deixe em branco para manter', accountConfigured: 'Conta configurada — o tablet pode se conectar', updatePassword: '🔑 Atualizar senha', noTablet: 'Nenhuma conta de tablet configurada', goToEmployees: 'Vá para Gestão de funcionários → Conta da loja', bonuses: '💰 Bônus dos funcionários', salesCommission: 'Comissão de vendas (%)', shiftBonus: 'Bônus por turno (€)', avgSaleThreshold: 'Limite venda média (€)', saveBonus: 'Salvar bônus', employeeFunctions: '👥 Funções do funcionário', employeeFunctionsDesc: 'Configure cada função acessível aos funcionários', saveAll: '💾 Salvar tudo', disabledFunctionsHint: 'Funções desativadas não aparecerão no painel do funcionário.', enableToConfig: '⚠️ Ative a função para configurar parâmetros', shopifyIntegration: '🛍️ Integração Shopify', shopifyDesc: 'Conecte sua loja Shopify para gerenciar pedidos diretamente do BrainWare.', shopifyDomain: 'Domínio Shopify', shopifyDomainHint: 'Apenas o domínio, ex: minhaloja.myshopify.com', accessToken: 'Access Token (Admin API)', autoSync: 'Sincronização automática ativa', saveShopify: 'Salvar Shopify', viewOrders: '👁️ Ver pedidos',
    feat_pos: 'POS / Venda', feat_pos_desc: 'Registrar vendas e gerenciar o carrinho', feat_shopify: 'Pedidos Shopify', feat_shopify_desc: 'Gestão de pedidos online', feat_fidelity: 'Cartões fidelidade', feat_fidelity_desc: 'Gestão de cartões fidelidade', feat_inventory: 'Contagem de inventário', feat_inventory_desc: 'Inventário e contagem de produtos', feat_stock: 'Reposição', feat_stock_desc: 'Adicionar quantidades aos produtos', feat_transfers: 'Transferências', feat_transfers_desc: 'Transferir produtos entre lojas', feat_expenses: 'Despesas', feat_expenses_desc: 'Registrar despesas durante o turno', feat_maintenance: 'Manutenção', feat_maintenance_desc: 'Checklist e manutenção', feat_photos: 'Registro de fotos', feat_photos_desc: 'Carregar fotos do caixa', feat_vending: 'Máquinas de venda', feat_vending_desc: 'Gestão de máquinas H24', feat_ai: 'Assistente IA', feat_ai_desc: 'Acesso ao assistente IA', feat_calendar: 'Dias de folga', feat_calendar_desc: 'Solicitações de licenças e férias', feat_checkout: 'Saída', feat_checkout_desc: 'Sair sem fechar o turno',
  },

  ai: {
    title: 'Inteligência IA', beta: 'BETA', dataLoaded: '✅ Dados carregados', loadingData: 'Carregando...', freeRequests: 'solicitações gratuitas', askAboutData: 'Pergunte algo sobre seus dados...', send: 'Enviar', howCanIHelp: 'Como posso ajudá-lo hoje?', analyzeDesc: 'Analise vendas, desempenho, inventário da sua loja em linguagem natural', suggestion1: 'Análise de vendas de hoje', suggestion2: 'Produtos com estoque baixo', suggestion3: 'Desempenho dos funcionários', suggestion4: 'Tendência de receita semanal', serviceDown: '⏳ Serviço IA temporariamente indisponível', serviceDownDesc: 'A cota diária foi atingida. Reinicia automaticamente em algumas horas.', dailyLimitReached: '🚫 Limite diário atingido', almostAtLimit: '⚠️ Quase no limite', newChat: '+ Novo',
  },

  emp: { title: '👤 Funcionários', addEmployee: 'Adicionar funcionário', fullName: 'Nome completo', pin: 'PIN', role: 'Função', store: 'Loja' },

  empApp: {
    home: 'Início', sale: 'Venda', inventory: 'Inventário', maintenance: 'Manutenção', restock: 'Reposição', aiAssistant: '🤖 Assistente IA', safeMode: '🔒 Modo seguro', safeDesc: 'Ajuda operacional · Sem acesso a dados comerciais', hello: 'Olá! Como posso ajudá-lo?', procAndTech: 'Procedimentos, problemas técnicos, gestão de clientes e mais', noSalesAccess: '🔒 Não tenho acesso a vendas, receitas ou dados comerciais. Só posso ajudar com procedimentos operacionais e problemas técnicos.', askSomething: 'Pergunte algo...', limitReached: 'Limite atingido por hoje', dailyLimitMsg: '⏳ Você atingiu o limite diário de solicitações. As solicitações são reiniciadas à meia-noite.',
  },

  members: { title: '💳 Membros', addMember: 'Adicionar membro', points: 'Pontos', totalSpent: 'Total gasto' },

  wh: { central: '🏭 Armazém central', secondary: '📦 Armazéns secundários', storeStock: '🏪 Estoque da loja', movements: '📋 Movimentos de estoque', sku: 'SKU', units: 'unidades', value: 'valor', lowItems: 'baixos', outOfStock: 'esgotados' },

  notif: { title: '🔔 Notificações', markRead: 'Marcar como lido', markAllRead: 'Marcar tudo como lido', noNotifications: 'Sem notificações' },
} as const

export default pt
